name: Pylint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the main.py code with pylint
      run: |
        pylint main.py
    - name: Moving to Scripts folder
      run: |
        cd /scripts
    - name: Analysing script folder .py files with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Back to home dir
      run: |
        cd ~
    - name: Going into dockerScripts folder
      run: |
        cd /docker_scripts
    - name: Analysing script folder .py files with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
        
           
