name: Pylint - Bhide Bhai

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing main.py code with pylint
      run: pylint --max-line-length=125 main.py 
      if: success()||failure()
    - run: cd scripts
    - name: Analysing scripts folder code with pylint
      run: |
        find . -type f -name '*.py' | xargs pylint --max-line-length=125
      if: success()||failure()
    - run: |
        cd ..
        cd docker_scripts
    - name:  Analysing docker scripts folder code with pylint  
      run: |
       find . -type f -name '*.py' | xargs pylint --max-line-length=125
     
           
      
           
