name: Pylint - Bhide Bhai

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing main.py code with pylint
      run: pylint main.py
      if: success()||failure()
    - name: Analysing scripts folder code with pylint
      run: |
        cd scripts
        pylint `ls -R|grep .py$|xargs`
      if: success()||failure()
    - name:  Analysing docker scripts folder code with pylint  
      run: |
        cd ..
        cd docker_scripts
        pylint `ls -R|grep .py$|xargs`
     
           
      
           
